CREATE TABLE IF NOT EXISTS contracts (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT REFERENCES counterparties(id) ON DELETE RESTRICT,
    branch_id INT REFERENCES branches(id) ON DELETE RESTRICT,
    contract_number VARCHAR NOT NULL,
    contract_name VARCHAR,
    contract_date DATE NOT NULL,
    delivery_date DATE,
    delivery_conditions TEXT,
    delivery_term_days INT,
    return_term_days INT,
    total_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    remaining_amount DECIMAL(18, 2) NOT NULL DEFAULT 0,
    contract_currency CHAR(3) NOT NULL,
    sender_account VARCHAR,
    receiver_name VARCHAR,
    receiver_account VARCHAR,
    receiver_country VARCHAR,
    additional_agreement TEXT,
    subject TEXT NOT NULL,
    contract_end_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
