ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE gtd ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE additional_agreements ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
