definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.RequestUser:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: API для управления клиентами, счетами, операциями и офисами банка
  title: Check Auth Active_Directory
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Проверяет учётные данные пользователя через Active Directory
      parameters:
      - description: Учётные данные пользователя
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.RequestUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            type: boolean
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
swagger: "2.0"
