// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/branches": {
            "get": {
                "description": "Возвращает список всех филиалов для экрана выбора.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branches"
                ],
                "summary": "Получение списка филиалов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.Branch"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard": {
            "get": {
                "description": "Возвращает список компаний с возможностью фильтрации по названию, сумме, ИНН и филиалу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Поиск для дашборда",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название компании",
                        "name": "company_name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Сумма контракта",
                        "name": "amount",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ИНН компании",
                        "name": "inn",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.DashboardSearchResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверные параметры",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies": {
            "post": {
                "description": "Создает новую компанию (контрагента) с обязательной привязкой к филиалу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "Создание новой компании (ҶДММ)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные для создания компании",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCompanyRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Обязательные поля не заполнены",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts": {
            "get": {
                "description": "Возвращает список контрактов для выбранной компании.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Получить список контрактов ЧДММ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Contract"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверные параметры",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый контракт",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Создание контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер контракта",
                        "name": "contract_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название контракта",
                        "name": "contract_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата контракта (YYYY-MM-DD)",
                        "name": "contract_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата поставки (YYYY-MM-DD)",
                        "name": "delivery_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата окончания контракта (YYYY-MM-DD)",
                        "name": "contract_end_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Срок поставки (дни)",
                        "name": "delivery_term_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Срок возврата (дни)",
                        "name": "return_term_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма контракта",
                        "name": "total_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта контракта",
                        "name": "contract_currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Счет отправителя",
                        "name": "sender_account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Наименование получателя",
                        "name": "receiver_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Счет получателя",
                        "name": "receiver_account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Страна получателя",
                        "name": "receiver_country",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Предмет",
                        "name": "subject",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Условия поставки",
                        "name": "delivery_conditions",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF документ",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Contract"
                        }
                    },
                    "400": {
                        "description": "Обязательные поля не заполнены",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/additional-agreements": {
            "get": {
                "description": "Возвращает список дополнительных соглашений по контракту.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdditionalAgreements"
                ],
                "summary": "Список доп. соглашений контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AdditionalAgreement"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает доп. соглашение к контракту. PDF обязателен. Все остальные поля опциональны.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdditionalAgreements"
                ],
                "summary": "Создать доп. соглашение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF файл доп. соглашения",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Новые условия доставки",
                        "name": "delivery_conditions",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Новый срок доставки (дней)",
                        "name": "delivery_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Новый срок возврата (дней)",
                        "name": "return_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Предмет соглашения",
                        "name": "subject",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Продлить срок контракта до (YYYY-MM-DD)",
                        "name": "extend_date_to",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма в иностранной валюте",
                        "name": "foreign_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта иностранной суммы (например USD)",
                        "name": "foreign_currency",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма в валюте контракта (прибавляется к лимиту)",
                        "name": "amount_in_contract_currency",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.AdditionalAgreement"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices": {
            "get": {
                "description": "Возвращает список инвойсов с ГТД, товарным остатком и PDF документами.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Список инвойсов контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.InvoiceWithDetails"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает инвойс. Если валюта инвойса совпадает с валютой контракта - поле deduct_amount не обязательно (берётся автоматически). Иначе обязательно.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Создать инвойс",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер инвойса",
                        "name": "invoice_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название инвойса",
                        "name": "invoice_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата инвойса (YYYY-MM-DD)",
                        "name": "invoice_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма инвойса (в валюте инвойса)",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта инвойса",
                        "name": "currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сколько списать с баланса контракта (обязательно, если валюты разные)",
                        "name": "deduct_amount",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "PDF файл",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Invoice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices/{invoice_id}/gtd": {
            "post": {
                "description": "Добавляет ГТД с файлом к инвойсу. closes_amount — сколько закрывается по инвойсу (в валюте инвойса).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Добавить ГТД к инвойсу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер ГТД",
                        "name": "gtd_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма ГТД (в валюте ГТД)",
                        "name": "gtd_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта ГТД (например EUR)",
                        "name": "gtd_currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата ГТД (YYYY-MM-DD)",
                        "name": "gtd_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сколько закрывается по инвойсу (в валюте инвойса)",
                        "name": "closes_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF файл ГТД",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.GTD"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/notifications": {
            "get": {
                "description": "Возвращает список контрактов, срок действия которых истекает в ближайшие 10 дней или уже истек.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Уведомления дашборда (контракты с истекающим сроком)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.NotificationResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/countries": {
            "get": {
                "description": "Поиск по справочнику стран. Можно использовать % для поиска по части слова (например, %еспублик%).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dictionary"
                ],
                "summary": "Поиск стран",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Строка для поиска",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.Country"
                            }
                        }
                    }
                }
            }
        },
        "/api/currencies": {
            "get": {
                "description": "Поиск по справочнику валют.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dictionary"
                ],
                "summary": "Поиск валют",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Строка для поиска (по названию или коду)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.Currency"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AdditionalAgreement": {
            "type": "object",
            "properties": {
                "amount_in_contract_currency": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "delivery_conditions": {
                    "type": "string"
                },
                "delivery_term_days": {
                    "type": "integer"
                },
                "document_path": {
                    "type": "string"
                },
                "extend_date_to": {
                    "type": "string"
                },
                "foreign_amount": {
                    "type": "number"
                },
                "foreign_currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "return_term_days": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "domain.Contract": {
            "type": "object",
            "properties": {
                "additionalAgreement": {
                    "type": "string"
                },
                "branchID": {
                    "type": "integer"
                },
                "clientID": {
                    "type": "integer"
                },
                "contractCurrency": {
                    "type": "string"
                },
                "contractDate": {
                    "type": "string"
                },
                "contractEndDate": {
                    "type": "string"
                },
                "contractName": {
                    "type": "string"
                },
                "contractNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deliveryConditions": {
                    "type": "string"
                },
                "deliveryDate": {
                    "type": "string"
                },
                "deliveryTermDays": {
                    "type": "integer"
                },
                "document_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "receiverAccount": {
                    "type": "string"
                },
                "receiverCountry": {
                    "type": "string"
                },
                "receiverName": {
                    "type": "string"
                },
                "remainingAmount": {
                    "type": "number"
                },
                "returnTermDays": {
                    "type": "integer"
                },
                "senderAccount": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.GTD": {
            "type": "object",
            "properties": {
                "closes_amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "document_path": {
                    "type": "string"
                },
                "gtd_amount": {
                    "type": "number"
                },
                "gtd_currency": {
                    "type": "string"
                },
                "gtd_date": {
                    "type": "string"
                },
                "gtd_number": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Invoice": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deduct_amount": {
                    "type": "number"
                },
                "document_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_date": {
                    "type": "string"
                },
                "invoice_name": {
                    "type": "string"
                },
                "invoice_number": {
                    "type": "string"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.InvoiceWithDetails": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deduct_amount": {
                    "type": "number"
                },
                "document_path": {
                    "type": "string"
                },
                "gtd": {
                    "$ref": "#/definitions/domain.GTD"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_date": {
                    "type": "string"
                },
                "invoice_name": {
                    "type": "string"
                },
                "invoice_number": {
                    "type": "string"
                },
                "invoice_remaining": {
                    "type": "number"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.CompanyResponse": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inn": {
                    "type": "string"
                },
                "llc": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCompanyRequest": {
            "type": "object",
            "properties": {
                "inn": {
                    "type": "string"
                },
                "llc": {
                    "type": "string"
                }
            }
        },
        "dto.DashboardSearchResult": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.NotificationResponse": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "contract_id": {
                    "type": "integer"
                },
                "contract_number": {
                    "type": "string"
                },
                "days_left": {
                    "type": "integer"
                },
                "effective_end_date": {
                    "type": "string"
                }
            }
        },
        "http.Branch": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "http.Country": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_ru": {
                    "type": "string"
                }
            }
        },
        "http.Currency": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name_ru": {
                    "type": "string"
                },
                "numeric_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Currency Control API",
	Description:      "API сервера для системы валютного контроля.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
