// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/branches": {
            "get": {
                "description": "Возвращает список всех филиалов для экрана выбора.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branches"
                ],
                "summary": "Получение списка филиалов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_delivery_http.Branch"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard": {
            "get": {
                "description": "Возвращает список компаний с возможностью фильтрации по названию, сумме, ИНН и филиалу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Поиск для дашборда",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название компании",
                        "name": "company_name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Сумма контракта",
                        "name": "amount",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ИНН компании",
                        "name": "inn",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.DashboardSearchResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверные параметры",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies": {
            "post": {
                "description": "Создает новую компанию (контрагента) с обязательной привязкой к филиалу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "Создание новой компании (ҶДММ)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные для создания компании",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.CreateCompanyRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Обязательные поля не заполнены",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}": {
            "put": {
                "description": "Позволяет администратору обновить данные компании",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Редактирование компании (ЧДММ)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.CreateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет администратору удалить компанию (soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удаление компании",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts": {
            "get": {
                "description": "Возвращает список контрактов для выбранной компании.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Получить список контрактов ЧДММ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_domain.Contract"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверные параметры",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый контракт",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Создание контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер контракта",
                        "name": "contract_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название контракта",
                        "name": "contract_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата контракта (YYYY-MM-DD)",
                        "name": "contract_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата поставки (YYYY-MM-DD)",
                        "name": "delivery_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата окончания контракта (YYYY-MM-DD)",
                        "name": "contract_end_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Срок поставки (дни)",
                        "name": "delivery_term_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Срок возврата (дни)",
                        "name": "return_term_days",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма контракта",
                        "name": "total_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта контракта",
                        "name": "contract_currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Счет отправителя",
                        "name": "sender_account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Наименование получателя",
                        "name": "receiver_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Счет получателя",
                        "name": "receiver_account",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Страна получателя",
                        "name": "receiver_country",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Предмет",
                        "name": "subject",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Условия поставки",
                        "name": "delivery_conditions",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF документ",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.Contract"
                        }
                    },
                    "400": {
                        "description": "Обязательные поля не заполнены",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}": {
            "put": {
                "description": "Позволяет администратору обновить данные контракта",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Редактирование контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер контракта",
                        "name": "contract_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Название контракта",
                        "name": "contract_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата контракта (YYYY-MM-DD)",
                        "name": "contract_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата поставки (YYYY-MM-DD)",
                        "name": "delivery_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата окончания контракта (YYYY-MM-DD)",
                        "name": "contract_end_date",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Срок поставки (дни)",
                        "name": "delivery_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Срок возврата (дни)",
                        "name": "return_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма контракта",
                        "name": "total_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта контракта",
                        "name": "contract_currency",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Счет отправителя",
                        "name": "sender_account",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Наименование получателя",
                        "name": "receiver_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Счет получателя",
                        "name": "receiver_account",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Страна получателя",
                        "name": "receiver_country",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Предмет",
                        "name": "subject",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Условия поставки",
                        "name": "delivery_conditions",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новый PDF документ (опционально)",
                        "name": "document",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.Contract"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет администратору удалить контракт (soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удаление контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/additional-agreements": {
            "get": {
                "description": "Возвращает список дополнительных соглашений по контракту.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdditionalAgreements"
                ],
                "summary": "Список доп. соглашений контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_domain.AdditionalAgreement"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает доп. соглашение к контракту.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AdditionalAgreements"
                ],
                "summary": "Создать доп. соглашение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF файл доп. соглашения",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер доп. соглашения",
                        "name": "agreement_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата доп. соглашения (YYYY-MM-DD)",
                        "name": "agreement_date",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Новые условия доставки",
                        "name": "delivery_conditions",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Новый срок доставки (дней)",
                        "name": "delivery_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Новый срок возврата (дней)",
                        "name": "return_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Предмет соглашения",
                        "name": "subject",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Продлить срок контракта до (YYYY-MM-DD)",
                        "name": "extend_date_to",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма платежа (в валюте платежа)",
                        "name": "foreign_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта платежа (например USD, EUR)",
                        "name": "foreign_currency",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма в валюте контракта (прибавляется к лимиту)",
                        "name": "amount_in_contract_currency",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.AdditionalAgreement"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/additional-agreements/{agreement_id}": {
            "put": {
                "description": "Позволяет администратору обновить данные доп. соглашения",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Редактирование доп. соглашения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID доп. соглашения",
                        "name": "agreement_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Условия поставки",
                        "name": "delivery_conditions",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Срок поставки",
                        "name": "delivery_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Срок возврата",
                        "name": "return_term_days",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Предмет соглашения",
                        "name": "subject",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Продлить до (YYYY-MM-DD)",
                        "name": "extend_date_to",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма платежа (в валюте платежа)",
                        "name": "foreign_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта платежа (например USD, EUR)",
                        "name": "foreign_currency",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма в валюте контракта (прибавляется к лимиту)",
                        "name": "amount_in_contract_currency",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новый PDF файл",
                        "name": "document",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.AdditionalAgreement"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет администратору удалить доп. соглашение",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удаление доп. соглашения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID доп. соглашения",
                        "name": "agreement_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices": {
            "get": {
                "description": "Возвращает список инвойсов с ГТД, товарным остатком и PDF документами.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Список инвойсов контракта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_domain.InvoiceWithDetails"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Создает инвойс.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Создать инвойс",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании (ЧДММ)",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер инвойса",
                        "name": "invoice_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название инвойса",
                        "name": "invoice_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата инвойса (YYYY-MM-DD)",
                        "name": "invoice_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма инвойса (в валюте инвойса)",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта инвойса",
                        "name": "currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сколько списать с баланса контракта (обязательно, если валюты разные)",
                        "name": "deduct_amount",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "PDF файл",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.Invoice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices/{invoice_id}": {
            "put": {
                "description": "Позволяет администратору обновить данные инвойса",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Редактирование инвойса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер инвойса",
                        "name": "invoice_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Наименование",
                        "name": "invoice_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата (YYYY-MM-DD)",
                        "name": "invoice_date",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма списания",
                        "name": "deduct_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта",
                        "name": "currency",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новый PDF файл",
                        "name": "document",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.Invoice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет администратору удалить инвойс",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удаление инвойса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices/{invoice_id}/gtd": {
            "get": {
                "description": "Возвращает ГТД, привязанную к указанному инвойсу.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Просмотр ГТД инвойса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_domain.GTD"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет ГТД с файлом к инвойсу.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Добавить ГТД к инвойсу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер ГТД",
                        "name": "gtd_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сумма ГТД (в валюте ГТД)",
                        "name": "gtd_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Валюта ГТД (например EUR)",
                        "name": "gtd_currency",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата ГТД (YYYY-MM-DD)",
                        "name": "gtd_date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Сколько закрывается по инвойсу (в валюте инвойса)",
                        "name": "closes_amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "PDF файл ГТД",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.GTD"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/companies/{company_id}/contracts/{contract_id}/invoices/{invoice_id}/gtd/{gtd_id}": {
            "put": {
                "description": "Позволяет администратору обновить данные ГТД",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Редактирование ГТД",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID ГТД",
                        "name": "gtd_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Номер ГТД",
                        "name": "gtd_number",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сумма ГТД",
                        "name": "gtd_amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Валюта ГТД",
                        "name": "gtd_currency",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Дата ГТД (YYYY-MM-DD)",
                        "name": "gtd_date",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Сколько закрывается по инвойсу",
                        "name": "closes_amount",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Новый PDF файл ГТД",
                        "name": "document",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CurrencyControl_internal_domain.GTD"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Позволяет администратору удалить ГТД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Удаление ГТД",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин администратора (admin)",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID компании",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID контракта",
                        "name": "contract_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID инвойса",
                        "name": "invoice_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID ГТД",
                        "name": "gtd_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/branches/{id}/dashboard/notifications": {
            "get": {
                "description": "Возвращает список контрактов, срок действия которых истекает в ближайшие 10 дней или уже истек.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Уведомления дашборда (контракты с истекающим сроком)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин пользователя",
                        "name": "Login",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID филиала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CurrencyControl_internal_delivery_dto.NotificationResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/countries": {
            "get": {
                "description": "Поиск по справочнику стран по части названия без учета регистра.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dictionary"
                ],
                "summary": "Поиск стран",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Строка для поиска",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_delivery_http.Country"
                            }
                        }
                    }
                }
            }
        },
        "/api/currencies": {
            "get": {
                "description": "Поиск по справочнику валют.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dictionary"
                ],
                "summary": "Поиск валют",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Строка для поиска (по названию или коду)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_delivery_http.Currency"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CurrencyControl_internal_delivery_dto.CompanyResponse": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inn": {
                    "type": "string"
                },
                "llc": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_delivery_dto.CreateCompanyRequest": {
            "type": "object",
            "properties": {
                "inn": {
                    "type": "string"
                },
                "llc": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_delivery_dto.DashboardSearchResult": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_delivery_dto.NotificationResponse": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "contract_id": {
                    "type": "integer"
                },
                "contract_number": {
                    "type": "string"
                },
                "days_left": {
                    "type": "integer"
                },
                "effective_end_date": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_domain.AdditionalAgreement": {
            "type": "object",
            "properties": {
                "agreement_date": {
                    "type": "string"
                },
                "agreement_number": {
                    "type": "string"
                },
                "amount_in_contract_currency": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "delivery_conditions": {
                    "type": "string"
                },
                "delivery_term_days": {
                    "type": "integer"
                },
                "document_path": {
                    "type": "string"
                },
                "extend_date_to": {
                    "type": "string"
                },
                "foreign_amount": {
                    "type": "number"
                },
                "foreign_currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "return_term_days": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_domain.Contract": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "client_id": {
                    "type": "integer"
                },
                "contract_currency": {
                    "type": "string"
                },
                "contract_date": {
                    "type": "string"
                },
                "contract_end_date": {
                    "type": "string"
                },
                "contract_name": {
                    "type": "string"
                },
                "contract_number": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "delivery_conditions": {
                    "type": "string"
                },
                "delivery_date": {
                    "type": "string"
                },
                "delivery_term_days": {
                    "type": "integer"
                },
                "document_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "receiver_account": {
                    "type": "string"
                },
                "receiver_country": {
                    "type": "string"
                },
                "receiver_name": {
                    "type": "string"
                },
                "remaining_amount": {
                    "type": "number"
                },
                "return_term_days": {
                    "type": "integer"
                },
                "sender_account": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_domain.GTD": {
            "type": "object",
            "properties": {
                "closes_amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "document_path": {
                    "type": "string"
                },
                "gtd_amount": {
                    "type": "number"
                },
                "gtd_currency": {
                    "type": "string"
                },
                "gtd_date": {
                    "type": "string"
                },
                "gtd_number": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_domain.Invoice": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deduct_amount": {
                    "type": "number"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "document_path": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_date": {
                    "type": "string"
                },
                "invoice_name": {
                    "type": "string"
                },
                "invoice_number": {
                    "type": "string"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "CurrencyControl_internal_domain.InvoiceWithDetails": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "contract_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deduct_amount": {
                    "type": "number"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "document_path": {
                    "type": "string"
                },
                "gtd": {
                    "$ref": "#/definitions/CurrencyControl_internal_domain.GTD"
                },
                "id": {
                    "type": "integer"
                },
                "invoice_date": {
                    "type": "string"
                },
                "invoice_name": {
                    "type": "string"
                },
                "invoice_number": {
                    "type": "string"
                },
                "original_document_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_delivery_http.Branch": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_delivery_http.Country": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_ru": {
                    "type": "string"
                }
            }
        },
        "internal_delivery_http.Currency": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name_ru": {
                    "type": "string"
                },
                "numeric_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Currency Control API",
	Description:      "API сервера для системы валютного контроля.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
